package com.example.demo

import java.util.*

enum class Roles {
    CUSTOMER,
    MANAGER,
    DEV,
    EMPLOYEE
}

enum class PaymentOption {
    CASH, CARD
}

enum class PaymentStatus {
    PENDING,
    SUCCESS,
    FAILED
}

enum class OrderStatus {
    ACCEPTED, PENDING, IN_PROGRESS, CANCELLED, COMPLETED, REFUNDED, READY, REJECTED
}

enum class ErrorCode(val code: Int) {
    GENERAL_ERROR(-1),
    USER_NOT_FOUND(-2),
    DUPLICATE_RESOURCE(-3),
    FORBIDDEN(-4),
    INVALID_INPUT(-5),
    RESOURCE_NOT_FOUND(-7),
    VALIDATION_ERROR(-8)
}

enum class UserStatus {
    EXISTS, CREATED, NOT_FOUND
}

enum class PaginationFieldName {
    PAGE,
    LIMIT
}

data class CardTypePattern(
    val pattern: Regex,
    val length: Int
)

enum class CardType(val pattern: Regex) {
    HUMO(Regex("^9860[0-9]{12}$")),
    UZCARD(Regex("^8600[0-9]{12}$")),
    VISA(Regex("^4[0-9]{12}(?:[0-9]{3})?$")),
    MASTERCARD(Regex("^5[1-5][0-9]{14}$"));
}

enum class BotState {
    START,
    AWAITING_LANGUAGE,
    AWAITING_PHONE,
    AWAITING_OTP,
    AWAITING_ADDRESS,
    AWAITING_ADDRESS_DETAILS,
    AWAITING_ADDRESS_SELECTION,
    REGISTERED,
    PRODUCT_DETAIL_VIEW
}

enum class MenuStates {
    MAIN_MENU,
    CATEGORY_VIEW,
    PRODUCT_VIEW,
    CART_VIEW,
    SETTINGS_VIEW,
    ADDRESSES_VIEW,
    PRODUCT_DETAIL_VIEW
}

/**
 * Enumeration of message keys used throughout the application.
 * These keys correspond to entries in the message property files.
 */
enum class MessageKey {
    // Welcome and registration messages
    WELCOME_MESSAGE,
    WELCOME_BACK,
    MY_ORDERS,
    REGISTER_PROMPT_PHONE,
    BUTTON_REGISTER_SHARE_PHONE,
    OTP_PROMPT,
    OTP_RETRY_PROMPT,
    ERROR_OTP_INVALID,

    ADDRESS_PROMPT,
    BUTTON_SHARE_LOCATION,
    ADDRESS_SAVED,
    ADDRESS_SELECTED,
    ADDRESS_LIST_TITLE,
    ADDRESS_NONE,
    ADDRESS_SELECT_OR_ADD,
    ADDRESS_PROVIDE_DETAILS,
    LOCATION_RECEIVED,
    PHONE_RECEIVED,

    MAIN_MENU_PROMPT,
    BUTTON_MENU,
    BUTTON_CART,
    BUTTON_MY_ADDRESSES,
    BUTTON_SETTINGS,
    BUTTON_RETURN,
    BUTTON_MAIN_MENU,

    CATEGORY_CHOOSE,
    PRODUCT_CHOOSE,
    PRODUCT_NONE_IN_CATEGORY,
    CATEGORY_NONE_AVAILABLE,

    LANGUAGE_SELECT,
    LANGUAGE_SELECTED,

    BUTTON_ADD_TO_CART,
    CART_ADDED_ITEM,
    CART_ADDED_ITEMS,
    BUTTON_VIEW_CART,
    BUTTON_CONTINUE_SHOPPING,
    CART_EMPTY,
    CART_TITLE,
    CART_TOTAL,
    BUTTON_CHECKOUT,

    CHECKOUT_SELECT_ADDRESS,
    CHECKOUT_NO_ADDRESSES,
    BUTTON_ADD_NEW_ADDRESS,
    BUTTON_CONFIRM_ORDER,
    BUTTON_CANCEL,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_FAILED,
    ORDER_ID,
    ORDER_TOTAL,

    ERROR_GENERIC,
    ERROR_INVALID_CONTACT,
    ERROR_INVALID_PHONE_NUMBER,
    ERROR_OTP_REQUEST_FAILED,
    ERROR_OTP_EXPIRED_OR_MISSING,
    ERROR_ADDRESS_SAVE_FAILED,
    ERROR_AUTH_REQUIRED,
    ERROR_PRODUCT_NOT_FOUND,
    ERROR_ADDRESS_NOT_FOUND,
    ERROR_CART_ADD_FAILED,
    ERROR_CHECKOUT,
    ERROR_ADDRESS_REQUIRED,
    ERROR_CART_VIEW_FAILED,
    ERROR_SEND_FAILED,
    ERROR_COMMAND_UNAVAILABLE,
    ERROR_SELECT_LANGUAGE_FIRST,
    ERROR_SHARE_CONTACT_FIRST,
    ERROR_ENTER_OTP_FIRST,
    ERROR_SHARE_LOCATION_FIRST,
    ERROR_SELECT_PRODUCT_FIRST,

    // Other messages
    UNKNOWN_COMMAND,
    HELP_TEXT,
    FEATURE_NOT_IMPLEMENTED,
    PRICE,

    // Validation error messages
    INVALID_INPUT,
    RESOURCE_NOT_FOUND,
    VALIDATION_ERROR,
    GENERAL_ERROR,
    DUPLICATE_RESOURCE,
    USER_NOT_FOUND,
    FORBIDDEN,
    OTP_REQUEST,
    PAYMENT_AMOUNT_MISMATCH,
    ORDER_ALREADY_CANCELLED,
    NEGATIVE_PRICE,
    INSUFFICIENT_BALANCE,
    INVALID_CARD_TYPE
}