spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: 2210
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
            show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000
      timeout: 1000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

management:
  health:
    redis:
      enabled: false
telegram:
  bot:
    name: ${Bot_Name}
    token: ${Bot_Token}
